[phases.setup]
nixPkgs = ['php81', 'php81Packages.composer', 'nodejs-18_x']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'chmod -R 755 storage',
    'chmod -R 755 bootstrap/cache'
]

[phases.build]
cmds = ['php artisan migrate --force']

[start]
cmd = 'php artisan optimize:clear && php artisan config:cache && php artisan view:cache && php -d variables_order=EGPCS -S 0.0.0.0:$PORT -t public public/index.php'
