[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs-18_x']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm install',
    'chmod -R 755 storage',
    'chmod -R 755 bootstrap/cache'
]

#[phases.build]
# Never run DB migrations during image build; database isn't reachable in build stage
#cmds = ['php artisan migrate --force']

[start]
cmd = 'php artisan config:clear && php artisan route:clear && php artisan view:clear && php artisan migrate --force --no-interaction || true && php -d display_errors=1 -d variables_order=EGPCS -S 0.0.0.0:$PORT -t public public/index.php'
